04 - Button + Accordion
js-tasks-ru/htmlcss-20240913_dimeliora710 pull request #4
Opened 2024-09-29 19:23 UTC by Dimeliora

Маркер всё же добавил, однако добиться адекватной анимации схлопывания/разворачивания пока не удалось. Анимирование `max-height` не работает, если контент лежит внутри `details`. Подожду секретов на лекции)

2024-09-29 19:24 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-10-04 20:05 UTC, GSemikozov commented
> Анимирование `max-height` не работает, если контент лежит внутри `details`

да, совершенно верно, никакого секрета, анимировать аккордион без фиксирования высоты или без js нельзя :)

2024-10-04 20:07 UTC, GSemikozov requested changes

2024-10-04 20:07 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +
line-height не хватает

2024-10-04 20:07 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +	cursor: default;
лишнее

2024-10-04 20:07 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_disabled {
.button:disabled

2024-10-04 20:07 UTC, GSemikozov commented on 03-lection1/01-button/index.html
> +        <button class="button button_primary button_disabled">Primary</button>
вместо класса button_disabled - атрибут disabled

2024-10-04 20:07 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +	padding: 24px 32px;
а какой отступ от текста тайтла до текста контента?

2024-10-04 20:42 UTC, Dimeliora commented on 03-lection1/02-accordion/accordion.css
> +	padding: 24px 32px;
16, это устанавливается в предпоследнем правиле. Согласно макету в схлопнутом состоянии по 24 сверху и снизу.

2024-10-04 21:00 UTC, Dimeliora commented on 03-lection1/01-button/button.css
> +	cursor: default;
В UA stylesheet для тега button у меня `cursor: default`, так что без этого никак.

2024-10-11 13:36 UTC, GSemikozov approved these changes

2024-10-11 13:37 UTC, merged