05 - Main grid with cards
js-tasks-ru/htmlcss-20240913_dimeliora710 pull request #6
Opened 2024-09-30 21:32 UTC by Dimeliora

Гистограмы пока нет в карточке, докину после апрува компонента.

2024-09-30 21:32 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-10-04 20:10 UTC, GSemikozov requested changes

2024-10-04 20:10 UTC, GSemikozov commented on index.html
> +                    <div class="card">
карточки - это ссылки, тот есть `<a>`

2024-10-11 13:38 UTC, GSemikozov approved these changes

2024-10-11 13:38 UTC, merged