06 - Tooltip
js-tasks-ru/htmlcss-20240913_dimeliora710 pull request #7
Opened 2024-10-03 20:10 UTC by Dimeliora

hover на самом tooltip, а не иконке для того, чтобы было доступно выделение и копирование текста из всплывающей подсказки.

2024-10-03 20:11 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-10-11 13:41 UTC, GSemikozov commented
> hover на самом tooltip, а не иконке для того, чтобы было доступно выделение и копирование текста из всплывающей подсказки.

нет, ховер можно и на блок поставить

2024-10-11 13:42 UTC, GSemikozov requested changes
конфликт

2024-10-13 07:25 UTC, GSemikozov approved these changes

2024-10-13 07:26 UTC, merged